import binary_search_tree from '../src/tree/binary_search_tree.js';
const tree = new binary_search_tree();
tree.insert(36);
tree.insert(27);
tree.insert(58);
tree.insert(6);
tree.insert(53);
tree.insert(69);
tree.insert(40);
tree.insert(64);
tree.insert(46);
tree.remove(36);
tree.trav_in((x) => console.log(x));
